### ISSUE TITLE
Reproducible packet error

### ISSUE THREAD

**Issue by fedekrum** [forkineye/ESPixelStick#697] opened 2023-12-02 03:31 UTC
**ESPixelStick Firmware Version**
FW Version 4.0-ci7063024905
Build Date Dec 1 2023 - 17:15:45

**Hardware Version**
Architecture ESP8266
Board Name espsv3 (Node MCU 1.0 v3)

**Binary release or compiled yourself?**
Binary release

**Operating System (and version)**
Macos Catalina

**Web Browser (and version)**
Chrome

**Access Point**
FritzBox 7490

**Describe the bug**
I can reproduce a Packet Error, but I am not sure if ESPixelStick is responsible for it or the sender.
I have made a script in Python using lib PyArtNet implementing E1.31 protocol. 
https://github.com/fedekrum/DMX/blob/main/scanDMX.py

usage: scanDMX.py [-h] -a ADDRESS -u UNIVERSE [-c CHANNEL] [-r RANGE]
                  [-s SPEED] [-k]

Scans DMX channels with PyArtNet.

options:
  -h, --help            show this help message and exit
  -a ADDRESS, --address ADDRESS
                        IP address or hostname of the sACN node
  -u UNIVERSE, --universe UNIVERSE
                        DMX universe number (1-63999)
  -c CHANNEL, --channel CHANNEL
                        DMX channel number (1-512), optional
  -r RANGE, --range RANGE
                        Range of channels to animate (1-512), optional
  -s SPEED, --speed SPEED
                        Animation speed in milliseconds (default 500ms)
  -k, --key-pause       Require key press to start animation for each channel

**How to reproduce**
1) Start fresh your ESPixelStick and notice **E1.31 Status** - **Packet Error** and **Total Packets** in zero.

![Captura de Pantalla 2023-12-02 a la(s) 4 11 16](https://github.com/forkineye/ESPixelStick/assets/4470683/f9cb2753-bc26-4796-a9d8-410b51c7b428)

2) Execute the script one time only
python3 scanDMX.py -a192.168.188.81 -u1 -c1
You will notice that xxx Total Packets were sent and no Packer Error will occur.

![Captura de Pantalla 2023-12-02 a la(s) 4 11 35](https://github.com/forkineye/ESPixelStick/assets/4470683/05eb561b-cb14-45d5-a1d5-56591be5aee1)

3) Execute the script once more
Notice that this time you get a Packet Error

![Captura de Pantalla 2023-12-02 a la(s) 4 11 50](https://github.com/forkineye/ESPixelStick/assets/4470683/7faad249-f2c5-42eb-b304-32e8ae2836dd)

4) If you keep repeating the execution you get one packet error each time, even if you change the command parameters to do an extensive scan.

![Captura de Pantalla 2023-12-02 a la(s) 4 12 06](https://github.com/forkineye/ESPixelStick/assets/4470683/8c78b5de-d401-4024-9e82-581f00f8fb11)

Thanks in advance

**Comment by fedekrum** [comment] 2023-12-04 09:36
I have simplified what the program does to have fewer packets to analyze (6 packets only).
I added Wireshark packets as a text report, .pcap and .pcapng.

**Comment by fedekrum** [comment] 2023-12-05 02:20
Thanks @MartinMueller2003 
So I assume that inside the E1.31 data, there is a sequential step number in each packet, right?
And the problem is that my program, each time it gets executed starts from step 0 (or 1) each time so the ESPixelStick gets that as a packet error, right?
Can you confirm if my interpretation is good?

If so, it should be more of a warning than a packet error.
I understand a packet error more as a packet loss because it is malformed.

**Comment by MartinMueller2003** [comment] 2023-12-05 12:57
Yes you are correct and yes it is a packet error. We cant tell if something dropped or got reset or was restarted or if a packet got delayed and then suddenly arrived late. So the simple to implement rule is: "Not the expected number? Increment error count".

**Comment by MartinMueller2003** [comment] 2023-12-06 00:00
can I close this as "not a bug"?

**Comment by fedekrum** [comment] 2023-12-06 23:44
Absolutely and thanks!!

**Closed** 2023-12-07 01:21 UTC
