### ISSUE TITLE
Web server fails after after AP fallback

### ISSUE THREAD

**Issue by lacuna2** [forkineye/ESPixelStick#389] opened 2021-10-13 20:39 UTC
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0 - beta 2
4.0 - beta 3 (ci1298554946)

**Hardware Version**
ESPixelstick V3.0

**Binary release or compiled yourself?**
ci1298554946

**Operating System (and version)**
Windows 10 - Version	10.0.19042 Build 19042

**Web Browser (and version)**
chrome 94.0.4606.81

**Access Point**
AP fallback

**Describe the bug**
I enter a Wifi SSID and password and enable AP fallback.
If the configured Wifi AP is not available, the device correctly switches to AP fallback mode.
I can connect to the Wifi and can ping to 192.168.4.1.
The browser however will not connect.  Wireshark shows the device is responding with connection resets.
The serial debugger stream shows listening on port 80 but no other info.

If I delete the configured Wifi SSID and password (leaving them blank), the AP fallback works correctly and I can browse management pages.

**Comment by forkineye** [comment] 2021-12-28 15:55
From looking at the logs, this seems to be a duplicate of https://github.com/forkineye/ESPixelStick/issues/378

**Closed by forkineye** 2021-12-28 15:55 UTC
Labels: Bug, Cant Reproduce

**Comment by lacuna2** [comment] 2021-12-28 21:28
still seeing this on beta4.
just wanted to note that I have isolated this to only samsung internet browser.
Other browser intermittently fail sometimes but recover gracefully and it is not generally a big problem...
