### ISSUE TITLE
Web interface inaccessible after several days

### ISSUE THREAD

**Issue by mattncsu** [forkineye/ESPixelStick#143] opened 2018-12-11 14:29 UTC
I have 9 ESPpixel sticks running on ESP-01s each controlling 50-200 pixels in unicast mode.  They are receiving E1.31 data from FPP on a Pi and a dedicated wifi access point. Everything has a manual IP address set up.

After a few days of uptime, I can no longer bring up the web interface, just a long pause before the browser times out.   I can ping the IP just fine (sub 5ms responses) and it is receiving E1.31 data and updating the attached pixels just fine, I just can't access the web interface. If I cycle the power, and hit refresh in the browser, the web interface comes right up without issue.  

Has anyone seen this behavior before? Is it possible that a timer is overflowing and disabling the web server?

**Comment by mattncsu** [comment] 2019-01-03 17:17
I don't have the exact version # on me now but it was the release version as of around 11/15 or so and I flashed it via the java applet.

**Comment by mattncsu** [comment] 2019-01-04 19:36
FW Version
3.1-dev

Build Date
Aug 4 2018

**Comment by Kamal-Sonani** [comment] 2019-02-26 04:41
Do continues click (untill saved popup massage)on **save changes** will help you..

Atleast works for me

**Comment by Kamal-Sonani** [comment] 2019-10-19 20:18
As last commented to till today i have some good news , In Google chrom there is some Issues to view websocket view of webpage of espixelstick

Try Internet Explorer , at least works for me

**Comment by forkineye** [comment] 2020-02-04 17:35
Closed due to inactivity

**Comment by mattncsu** [comment] 2020-02-04 17:44
I forgot this was out there. I updated all my boards to the latest version in December. I still had the same issue of sometimes not being able to pull up the web interface for boards that were pingable and pushing out e1.31 data to pixels just fine.  I attribute it to the ESP being too busy to respond to the http request but I haven't done much testing--its usually easier to just cycle the power.

**Comment by forkineye** [comment] 2020-02-04 17:51
The next it happen, can you stop the e131 source and see if that helps?  Will help me narrow down the issue, thanks.

**Comment by mattncsu** [comment] 2020-02-04 18:03
Will do. However, I've put away my pixelsticks until next November so if you want to keep the issue closed for housekeeping purposes, I understand completely.

**Comment by mkozik13** [comment] 2020-09-09 02:43
I tend to have the same issues with this.  The shell of the page will populate but none of the data within.  Have to reboot the D1 Mini to get it to start working properly.  This evening, it happened and there was not e131 source yet as it was stilled turned off in the FPP.  I am running 3.1 from April 2020

**Comment by traketal** [comment] 2020-11-18 05:09
I run D1 minis and D1 mini pros. I have the exact same problem. Web UI loads, but all data is blank. I'm on 3.1. I had this same problem last year as well on other versions. I can ping them, and they still receive data from FPP, but I can't view or make changes to the controllers. In fact, I loaded 3.1 on 15 d1 minis, and same behaviour on all of them. After flashing, I can load the UI, and make any changes, but after I close the browser, I can never get back in to settings. Even rebooting esp doesn't help.

**Comment by forkineye** [comment] 2020-12-01 14:11
I've been unable to reproduce this. I've had modules running for over a week without any web access issues on both 3.1 and 3.2.  For you that are having issues, are you using the binary I provide or compiling yourself?  Also, some shots from Chrome's DevTools Network tab (F12 -> Network) could provide useful data on what's going on.

**Comment by phorsfi** [comment] 2020-12-07 23:06
while waiting for load and after pressing stop...

if i restart the wemos D1 Mini the web interface will load fine 2-3 times before this starts happening again...
![Screenshot 2020-12-07 150438](https://user-images.githubusercontent.com/74896209/101415983-ba352c80-389d-11eb-9815-d872f32cadde.png)
![Screenshot 2020-12-07 150503](https://user-images.githubusercontent.com/74896209/101415984-bacdc300-389d-11eb-8ea4-6f7af027c3b8.png)

**Comment by forkineye** [comment] 2020-12-21 14:19
Data not populating due to the websocket connection not happening.  What browser versions are being used?

**Comment by MartinMueller2003** [comment] 2020-12-26 15:26
I set up an ESP8266 version to play a 2 minute sequence from the local SD card. It has been running for two days. No problem accessing the UI.
Martin
    On Monday, December 21, 2020, 09:20:05 AM EST, Shelby Merrick <notifications@github.com> wrote:  
 
 


Data not populating due to the websocket connection not happening. What browser versions are being used?

**Comment by Tom-W3SF** [comment] 2020-12-29 05:22
I also have this issue.  I have 12 ea. version 1 boards, each running a single 48 pixel snowflake, each on it's own 5 volt 2.5 amp supply.  xLights computer is NOT running, no e1.31 data.  These ESP-01 boards are running rainbow test pattern, enabled at boot.  Running manual assigned fixed IPs on 10.10.10.xx /24 lan segment.  Pixel Stick home page comes up, but no data.  Mostly times out, reloading the page several times yields success.  This was an issue with version 2 firmware when I started playing with these in 2018.  Updated to 3.1-dev. fw in January 2019 - still same problem.  Updated to v. 3.2 build date 11/3/2020 - still an issue with the ESP-01 boards.  As a test, I purchased a forkineye v3.0 board from Amazon last week.  Loaded it by USB CH340 driver with the provided binary ver 3.2 build 11/3/2020 - It does the same thing.  With 6 or so refreshes, I can get into the homepage.  Once in, I can navigate between all the ESPS pages with no delays and all data present.  Having the issue with Google Chrome, Fire Fox, Edge on the Win10, and using Edge & Chrome on my Galaxy S9+ Android device.  Only common thread is my network devices and router, a LinkSys WRT3200ACM, which had it's firmware updated to factory latest this week also.  Next thought would be to power down all other network pc, printer, raspberry pi, phones, tvs, stereo rcvr, etc. and see if any different.  Could configure another router just for pc and pixel sticks.  Be happy to conduct experiments if I receive suggestions!  Thank you

**Comment by MartinMueller2003** [comment] 2021-01-10 04:10
I just let one of my unify ESPs run for three days. No issue accessing the UI.

**Comment by patdelaney** [comment] 2021-01-10 23:20
Same here   3 days 10 hours 2 outputs configured

**Comment by Tom-W3SF** [comment] 2021-01-13 17:26
Two Different Pixel Sticks 10.10.10.120 which is a new version 3 hardware, and .121 which is a 3 year old version 1 hardware.  Both devices are running FW version 3.2 Build Date Nov 3 2020.  Used provided binary to load these.

2 ea. jpg screen shots attached to this email.

Thank you!

**Comment by Tom-W3SF** [comment] 2021-01-13 17:36
![ESPixel HW 3 0 Chrome Error 1-13-2021](https://user-images.githubusercontent.com/76713864/104488021-d06c9180-559b-11eb-9eab-28bc1b7fd110.jpg)
![ESPixel HW 1 0 Chrome Error 1-13-2021](https://user-images.githubusercontent.com/76713864/104488022-d1052800-559b-11eb-955b-81f2c3908987.jpg)

**Comment by MartinMueller2003** [comment] 2021-03-04 13:34
That picture indicates the socket has gone down and that you are using V1/2/3 software. 
We are not seeing this in the V4 software.

The fact that the page loaded at all indicates the ESP is not dead. Please issue the command 10.10.10.121/heap via the browser. This will let us know if there has been a memory leak.

**Comment by forkineye** [comment] 2021-09-23 23:00
Not experiencing in current code, closing.

**Closed by forkineye** 2021-09-23 23:00 UTC
